Repository micronaut-projects/micronaut-security, pull requests merged in 2020-08, with the labels that each got.

#342 Dependency upgrades
  security-jwt/build.gradle
Labels: type: dependency-upgrade

#345 Update rejectNotFound.adoc, boolean value is incorrect in doc
  src/main/docs/guide/securityConfiguration/rejectNotFound.adoc
Labels: type: docs

#349 Dependency upgrades
  security-oauth2/build.gradle
  test-suite-kotlin/build.gradle
Labels: type: dependency-upgrade

#347 [security] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#353 test: simplify state parsing
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/StateUtils.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OauthAuthorizationRedirectSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectOauthDisabledSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectWithJustOpenIdSpec.groovy
Labels: type: improvement

#352 test: bean of type NonceConfiguration by default
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/nonce/NonceConfigurationSpec.groovy
Labels: relates-to: oidc, type: improvement

#351 log: better logging if nonce validator fails
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
Labels: type: improvement

#358 feat: allow NonceClaimValidator to be disabled
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/NonceClaimValidator.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/NonceClaimValidatorDisableSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/validation/NonceClaimValidatorSpec.groovy
Labels: type: improvement

#356 docs: Improve documentation about nonce
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-auth-parameters/nonce.adoc
Labels: type: docs

#350 refactor: move JWTValidator logging to trace level
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtValidator.java
Labels: type: improvement

#360 build: revert to kotlin 1.3.72
  security-oauth2/build.gradle
  test-suite-kotlin/build.gradle
Labels: lang: kotlin, relates-to: build, type: dependency-upgrade

#357 refactor: extract two proteced methods to simplify override
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
Labels: type: improvement
