Repository micronaut-projects/micronaut-security, pull requests merged in 2020-12, with the labels that each got.

#477 bump up gradle to 6.7.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#478 ci: github actions and MANTAINING.md
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  MAINTAINING.md
Labels: relates-to: build

#503 ci: update github actions
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#509 buil: bump up micronaut test to 2.3.1
  gradle.properties
Labels: relates-to: build

#489 Fix typo in sample
  src/main/docs/guide/oauth/flows/clientcredentials.adoc
Labels: type: docs

#510 doc: maven group is io.micronaut.security
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-auth-parameters/nonce.adoc
  src/main/docs/guide/oauth/flows/authorization-code/state.adoc
  src/main/docs/guide/oauth/installation.adoc
  src/main/docs/guide/oauth/openid.adoc
Labels: type: docs

#511 fix: AttributesConvertibleValues protect NPE
  security-ldap/src/main/java/io/micronaut/configuration/security/ldap/context/AttributesConvertibleValues.java
  security-ldap/src/test/groovy/io/micronaut/configuration/security/ldap/context/AttributesConvertibleValuesSpec.groovy
Labels: type: bug

#508 refactor: no need to create a userdetails
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/DefaultJwtAuthenticationFactory.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/DefaultJwtAuthenticationFactorySpec.groovy
Labels: type: improvement

#517 ci: set github branch to 2.2.x
  gradle.properties
Labels: relates-to: build

#516 ci: set github core to 2.3.x
  gradle.properties
Labels: relates-to: build

#515 build: set project version to 2.3.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#518 refactor: fields @NonNull @Nullable annotations
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
Labels: type: improvement

#519 feat: add equals and hashcode to TokenResponse
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
Labels: type: improvement

#523 fix: don’t clear if element is null
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/AbstractClientCredentialsClient.java
Labels: type: improvement

#524 refactor: extract method and clarify javadoc
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/AbstractClientCredentialsClient.java
Labels: type: improvement

#521 refactor: add expiration to TokenResponse
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/AbstractClientCredentialsClient.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/CacheableProcessor.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseExpiration.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
Labels: type: improvement

#520 refactor: Token Response Constructor for required fields
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponse.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
Labels: type: improvement
