Repository micronaut-projects/micronaut-security, pull requests merged in 2020-09, with the labels that each got.

#367 [security] Update common files for branch master
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#382 doc: fix broken link to javadoc
  src/main/docs/guide/breaks.adoc
Labels: type: docs

#387 bump up micronaut test to 2.0.0
  gradle.properties
Labels: relates-to: build

#392 doc: Add release History section
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#398 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#400 checkstyle: remove unused import
  security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/KeysController.java
Labels: type: improvement

#399 refactor: extract basic auth parsing to its own class
  security/src/main/java/io/micronaut/security/authentication/BasicAuthAuthenticationFetcher.java
  security/src/main/java/io/micronaut/security/authentication/BasicAuthUtils.java
  security/src/test/groovy/io/micronaut/security/authentication/BasicAuthUtilsSpec.groovy
Labels: type: improvement

#404 refactor: split DefaultOpenIdAuthorization methods
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultOpenIdAuthorizationResponseHandler.java
Labels: type: improvement

#407 feat: annotate address with @Introspected
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/Address.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/AddressSpec.groovy
Labels: type: improvement
