Repository micronaut-projects/micronaut-security, pull requests merged in 2020-10, with the labels that each got.

#423 test: bump up geb to 3.4.1
  gradle.properties
Labels: type: dependency-upgrade

#424 bump up micronaut test to 2.2.0
  gradle.properties
Labels: type: dependency-upgrade

#426 test: Test TokenResponse uses snake case
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
Labels: type: improvement

#425 fix: client credential grant scope not scopes
  security-oauth2/src/main/java/io/micronaut/security/oauth2/grants/ClientCredentialsGrant.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/grants/ClientCredentialsGrantSpec.groovy
Labels: type: bug

#427 bump up project version to 2.2.0.BUILD-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#431 refactor: move getTokenEndpoint to interface
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOauthClient.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthClientConfiguration.java
Labels: type: improvement

#433 refactor: getTokenEndpointAuthMethods to interface
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdClient.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/OpenIdProviderMetadata.java
Labels: type: improvement

#432 bump up micronaut test to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade
