Repository micronaut-projects/micronaut-security, pull requests merged in 2020-11, with the labels that each got.

#443 bump up micronaut to 2.1.3
  gradle.properties
Labels: relates-to: build

#444 ci: bump up micronaut to 2.1.3
  gradle.properties
Labels: relates-to: build

#445 [security] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .gitignore
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#446 [security] Update common files for branch 2.1.x
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .gitignore
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#449 [security] Update common files for branch 2.1.x
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#448 [security] Update common files for branch master
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#450 refactor: Use constant Filter.MATCH_ALL_PATTERN
  security/src/main/java/io/micronaut/security/filters/SecurityFilter.java
Labels: type: improvement

#454 [security] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/release-notes.yml
Labels: relates-to: build

#455 [security] Update common files for branch 2.1.x
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/release-notes.yml
Labels: relates-to: build

#457 build: bump up to gradle 6.7.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#458 doc: Clafiy JWT Signature verification/generation
  src/main/docs/guide/authenticationStrategies/jwt/jwtEncryption.adoc
  src/main/docs/guide/authenticationStrategies/jwt/jwtEncryption/jwtGeneratorEncryption.adoc
  src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorRSA.adoc
  src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSecret.adoc
  src/main/docs/guide/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSignature.adoc
  src/main/docs/guide/authenticationStrategies/jwt/jwtValidation.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#459 test: Keycloak can be ignored sys testcontainers
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/Keycloak.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/e2e/AuthenticationModeIdTokenSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/e2e/OpenIdAuthorizationCodeSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectOauthDisabledSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectWithJustOpenIdSpec.groovy
Labels: relates-to: build

#461 Bump up GraalVM from 20.2.0 to 20.3.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#462 doc: clarify claims validation
  src/main/docs/guide/authenticationStrategies/jwt/claimsValidation.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#460 Bump graalvm to 20.3.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#442 bump up testcontainers to 1.15.0
  security-oauth2/build.gradle
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/Keycloak.groovy
Labels: type: dependency-upgrade

#456 feat: add idtoken claims validation for authentication mode idtoken
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/IdTokenClaimsValidatorAuthenticationIdTokenButDisabledSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/IdTokenClaimsValidatorAuthenticationIdTokenSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/IdTokenClaimsValidatorSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/JwksUriSignatureSpec.groovy
  src/main/docs/guide/authenticationStrategies/jwt/claimsValidation.adoc
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/token-validation.adoc
Labels: type: enhancement

#468 doc: Fix to Client Credentials Filter javadoc
  src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Labels: type: docs

#467 fix links to ClientCredentialsClient javadoc
  src/main/docs/guide/oauth/flows/clientcredentials.adoc
Labels: type: docs

#472 bump up github action create-pull-request to 3.5.1
  .github/workflows/dependency-update.yml
Labels: relates-to: build
