Repository micronaut-projects/micronaut-security, pull requests merged in 2021-05, with the labels that each got.

#644 fix: Support absolute configs for oauth callback and login
  security-oauth2/src/main/java/io/micronaut/security/oauth2/url/DefaultOauthRouteUrlBuilder.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/url/OauthRouteUrlBuilderSpec.groovy
Labels: type: bug

#651 build: gradle to 7.0.2 and graalvm from 21.0.2 to 21.0.1.0
  .github/workflows/graalvm.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#672 BREAKING CHANGE: delete getTokenEndpoint
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOauthClient.java
Labels: status: next major version

#669 BREAKING CHANGE: del DefaultSecurityService#ROLES
  security/src/main/java/io/micronaut/security/utils/DefaultSecurityService.java
Labels: status: next major version

#656 BREAKING CHANGE: del createUserDetails(TokenResponse)
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/OauthUserDetailsMapper.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OauthAuthorizationRedirectSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectOauthDisabledSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/endpoint/CsrfFilterSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/github/GithubUserDetailsMapper.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/github/GithubUserDetailsMapper.kt
  test-suite/src/test/java/io/micronaut/security/oauth2/docs/github/GithubUserDetailsMapper.java
Labels: status: next major version

#657 BREAKING CHANGE: del TokenValidator::validateToken(String)
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestNotPassedByDefaultSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestPassedSpec.groovy
  security/src/main/java/io/micronaut/security/token/validator/TokenValidator.java
  security/src/test/groovy/io/micronaut/security/endpoints/introspection/IntrospectionAuthorizerSpec.groovy
  security/src/test/groovy/io/micronaut/security/endpoints/introspection/IntrospectionControllerPathConfigurableSpec.groovy
  security/src/test/groovy/io/micronaut/security/endpoints/introspection/IntrospectionControllerSpec.groovy
Labels: status: next major version

#659 BREAKING CHANGE: SessionLoginHandler constructor
  security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java
Labels: status: next major version

#658 BREAKING CHANGE: del TokenRefreshRequest(String)
  security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/TokenRefreshRequest.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/OauthControllerPathConfigurableSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/OauthControllerSpec.groovy
Labels: status: next major version

#660 BREAKING CHANGE: delete SecurityService:hasRole
  security/src/main/java/io/micronaut/security/utils/DefaultSecurityService.java
  security/src/main/java/io/micronaut/security/utils/SecurityService.java
Labels: status: next major version

#671 BREAKING CHANGE: del TokenResponseExpiration
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseExpiration.java
Labels: status: next major version

#670 BREAKING CHANGE: constr DefaultSecurityService
  security/src/main/java/io/micronaut/security/utils/DefaultSecurityService.java
  security/src/test/groovy/io/micronaut/security/authorization/SecuredRolesCaseSensitiveSpec.groovy
Labels: status: next major version

#668 BREAKING CHANGE: del createAuthenticationResponse
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/DefaultOpenIdUserDetailsMapper.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/OpenIdUserDetailsMapper.java
  test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/openid/GlobalOpenIdUserDetailsMapper.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/openid/GlobalOpenIdUserDetailsMapper.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/openid/OktaUserDetailsMapper.kt
  test-suite/src/test/java/io/micronaut/security/oauth2/docs/openid/GlobalOpenIdUserDetailsMapper.java
  test-suite/src/test/java/io/micronaut/security/oauth2/docs/openid/OktaUserDetailsMapper.java
Labels: status: next major version

#661 BREAKING CHANGE: del parseCredentials
  security/src/main/java/io/micronaut/security/authentication/BasicAuthAuthenticationFetcher.java
  security/src/test/groovy/io/micronaut/security/authentication/BasicAuthAuthenticationFetcherSpec.groovy
Labels: status: next major version

#662 BREAKING CHANGE: JwtGeneratorConfiguration
  security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/JwtGeneratorConfiguration.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/JwtGeneratorConfigurationProperties.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/JwtGeneratorConfigurationPropertiesSpec.groovy
Labels: status: next major version

#665 BREAKING CHANGE: del JwtClaimsValidator:validate
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/AudienceJwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/ExpirationJwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/IssuerJwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/NotBeforeJwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/SubjectNotNullJwtClaimsValidator.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestNotPassedByDefaultSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestPassedSpec.groovy
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
Labels: status: next major version

#663 BREAKING CHANGE: del JWTClaimsSetGenerator constru
  security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/claims/JWTClaimsSetGenerator.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/generator/claims/JWTClaimsSetGeneratorSpec.groovy
Labels: status: next major version

#664 BREAKING CHANGE: RefreshTokenGeneratedEvent constr
  security/src/main/java/io/micronaut/security/token/event/RefreshTokenGeneratedEvent.java
Labels: status: next major version

#655 doc: links to cognito and google guides
  src/main/docs/guide/oauth.adoc
Labels: type: docs

#652 doc: update links to guides
  src/main/docs/guide/authenticationStrategies/basicAuth.adoc
  src/main/docs/guide/authenticationStrategies/jwt/reader/bearerToken.adoc
  src/main/docs/guide/authenticationStrategies/jwt/reader/cookieToken.adoc
  src/main/docs/guide/authenticationStrategies/session.adoc
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/ldap.adoc
  src/main/docs/guide/oauth.adoc
  src/main/docs/guide/tokenPropagation.adoc
Labels: type: docs

#653 doc: link to github and linked in guides
  src/main/docs/guide/oauth/flows/authorization-code/oauth2-authorization-code/oauth2-user-details.adoc
Labels: type: docs

#674 BREAKING CHANGE: del JwtCookieConfiguration
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/CookieLoginHandler.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandler.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfiguration.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieLoginHandler.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieTokenReader.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/CookieEnabledSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationOverrideSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestNotPassedByDefaultSpec.groovy
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/IdTokenLoginHandler.java
Labels: status: next major version

#673 BREAKING CHANGE: DefaultOpenIdUserDetailsMapper
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/DefaultOpenIdUserDetailsMapper.java
Labels: status: next major version

#667 BREAKING CHANGE: deprecated JwtValidator::validate
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtValidator.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
Labels: status: next major version

#666 BREAKING CHANGE: SecuritySessionConfiguration
  security-session/src/main/java/io/micronaut/security/session/SecuritySessionConfiguration.java
  security-session/src/main/java/io/micronaut/security/session/SecuritySessionConfigurationProperties.java
  security-session/src/main/java/io/micronaut/security/session/SessionLogoutHandler.java
  security-session/src/test/groovy/io/micronaut/security/session/SecuritySessionConfigurationOverrideSpec.groovy
  security-session/src/test/groovy/io/micronaut/security/session/SecuritySessionConfigurationSpec.groovy
Labels: status: next major version
