Repository micronaut-projects/micronaut-security, pull requests merged in 2021-04, with the labels that each got.

#613 build: bump up nimbusJoseJwt from 9.7 to 9.8
  security-jwt/build.gradle
Labels: type: dependency-upgrade

#614 ci: set up github core branch to 2.5.x
  gradle.properties
Labels: relates-to: build

#615 ci: GitHub action files
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#618 build: bump up Nimbus JOSE JWT from 9.8 to 9.8.1
  security-jwt/build.gradle
Labels: type: dependency-upgrade

#619 docs: improve documentation about SensitiveEndpointRule replacement
  security/src/main/java/io/micronaut/security/rules/SensitiveEndpointRule.java
  src/main/docs/guide/securityRule/builtInEndpointsAccess.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/LoggerSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.groovy
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/groovy/io/micronaut/security/oauth2/docs/ConfigurationFixture.groovy
  test-suite-kotlin/src/test/groovy/io/micronaut/security/oauth2/docs/EmbeddedServerSpecification.groovy
  test-suite-kotlin/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/LoggersSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.kt
  test-suite/src/test/groovy/io/micronaut/security/oauth2/docs/ConfigurationFixture.groovy
  test-suite/src/test/groovy/io/micronaut/security/oauth2/docs/EmbeddedServerSpecification.groovy
  test-suite/src/test/groovy/io/micronaut/security/oauth2/docs/managementendpoints/LoggersSpec.groovy
  test-suite/src/test/java/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.java
Labels: type: improvement

#620 refactor: use micronaut nullability annotations
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/AudienceJwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/IssuerJwtClaimsValidator.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorConfiguration.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorConfigurationProperties.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/NotBeforeJwtClaimsValidator.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/AudienceJwtClaimsValidatorSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/IssuerJwtClaimsValidatorSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/NotBeforeJwtClaimsValidatorSpec.groovy
Labels: type: improvement

#631 fix: use a Memoized supplier for DefaultTokenClient
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/DefaultTokenEndpointClient.java
Labels: type: bug

#632 docs: fix configuration properties tables
  src/main/docs/guide/authenticationStrategies/ldap/configuration.adoc
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-auth-parameters.adoc
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-configuration.adoc
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-user-details.adoc
  src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
  src/main/docs/guide/oauth/oauth-endpoints/endsession.adoc
  src/main/docs/guide/oauth/oauth-endpoints/introspection.adoc
  src/main/docs/guide/oauth/oauth-endpoints/revocation.adoc
  src/main/docs/guide/oauth/oauth-endpoints/user-info.adoc
  src/main/docs/guide/securityConfiguration/redirection.adoc
Labels: type: docs
