Repository micronaut-projects/micronaut-security, pull requests merged in 2021-06, with the labels that each got.

#684 build: Github actions update
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
Labels: relates-to: build

#690 fix: BeanProvider instead of Provider
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/JwksUriSignatureFactory.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/OpenIdClientFactory.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsFactory.java
Labels: type: improvement

#692 test: remove pending feature
  security/src/test/groovy/io/micronaut/security/endpoints/introspection/IntrospectionResponseSpec.groovy
Labels: type: improvement

#704 test: AuthenticationUserDetailsAdapter @Introspected
  security/src/test/groovy/io/micronaut/security/authentication/AuthenticationUserDetailsAdapterSpec.groovy
Labels: type: improvement

#705 build: remove geckodriverVersion
  gradle.properties
Labels: relates-to: build

#707 doc: changes in Micronaut security 3
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/whatsNew.adoc
Labels: type: docs
