Repository micronaut-projects/micronaut-security, pull requests merged in 2021-01, with the labels that each got.

#535 [security] Update common files for branch master
  .github/dependabot.yml
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#538 build: bump up gradle to 6.8
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#539 doc: fix copy in client-credentials section
  src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Labels: type: docs

#542 build: micronaut test to 2.3.2
  gradle.properties
Labels: relates-to: build

#544 test: run PermitAllSpec
  gradle.properties
  security/build.gradle
  security/src/test/groovy/io/micronaut/docs/security/securityRule/permitall/PermitAllSpec.groovy
  security/src/test/java/io/micronaut/docs/security/securityRule/permitall/ExampleController.java
  src/main/docs/guide/securityRule/secured.adoc
Labels: relates-to: build

#545 build: bump up geb to 4.0
  gradle.properties
  security-oauth2/build.gradle
Labels: relates-to: build

#548 fix: :%s/CacheableProcessor/RxJava cache operator
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/AbstractClientCredentialsClient.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/CacheableProcessor.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/clientcredentials/ClientCredentialsConcurrentSpec.groovy
Labels: type: bug
