Repository micronaut-projects/micronaut-security, pull requests merged in 2021-02, with the labels that each got.

#551 docs: security->oauth2->client_cerdentials: fix typo in secret, optimize params
  src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Labels: type: docs

#557 refactor: IdTokenClaimsValidator
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java
Labels: type: improvement

#556 javadoc: default scopes in configuration reference
  security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/OauthClientConfigurationProperties.java
Labels: type: docs

#567 ci: updates actions & Gradle 6.8.2
  .github/workflows/bintray-publish.yml
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  MAINTAINING.md
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#573 [security] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#576 [security] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#578 [security] Update common files for branch master
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
