Repository micronaut-projects/micronaut-security, pull requests merged in 2021-09, with the labels that each got.

#767 build: bump up to Gradle 7.2
  gradlew
Labels: relates-to: build

#772 doc: same-site is case sensitive
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/RefreshTokenCookieConfigurationProperties.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieSameSiteCaseSensitiveSpec.groovy
Labels: type: docs

#775 Add jakarta security annotation mapping
  security-annotations/src/main/java/io/micronaut/security/annotation/DenyAllAnnotationMapper.java
  security-annotations/src/main/java/io/micronaut/security/annotation/JakartaDenyAllAnnotationMapper.java
  security-annotations/src/main/java/io/micronaut/security/annotation/JakartaPermitAllAnnotationMapper.java
  security-annotations/src/main/java/io/micronaut/security/annotation/JakartaRolesAllowedAnnotationMapper.java
  security-annotations/src/main/java/io/micronaut/security/annotation/PermitAllAnnotationMapper.java
  security-annotations/src/main/java/io/micronaut/security/annotation/RolesAllowedAnnotationMapper.java
  security-annotations/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  security/src/test/groovy/io/micronaut/security/denyall/JakartaDenyAllSpec.groovy
  security/src/test/groovy/io/micronaut/security/permitall/JakartaPermitAllSpec.groovy
  security/src/test/groovy/io/micronaut/security/rolesallowed/JakartaRolesAllowedSpec.groovy
  src/main/docs/guide/securityRule/secured.adoc
Labels: type: enhancement

#786 Update section title
  src/main/docs/guide/toc.yml
Labels: type: docs

#794 test: check @ReflectiveAccess annotation present
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/DefaultOpenIdProviderMetadataSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/state/DefaultStateSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/OpenIdTokenResponseSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/token/response/TokenResponseSpec.groovy
Labels: type: improvement

#795 Enable build scans
  settings.gradle
Labels: relates-to: build

#796 feat: Add roles-separator to split roles from attributes
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/roles/RolesSeparatorSpec.groovy
  security/src/main/java/io/micronaut/security/token/DefaultRolesFinder.java
  security/src/main/java/io/micronaut/security/token/config/TokenConfiguration.java
  security/src/main/java/io/micronaut/security/token/config/TokenConfigurationProperties.java
Labels: type: improvement
