Repository micronaut-projects/micronaut-security, pull requests merged in 2021-07, with the labels that each got.

#723 Fix: Typo in doc (#717)
  src/main/docs/guide/oauth/flows/clientcredentials/clientecredentialshttpclient.adoc
Labels: type: docs

#708 build: update GitHub actions and Gradle to 7.1.1
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#729 ci: update to GraalVM from 21.1.0 to 21.2.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#733 New issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new_feature.yaml
  .github/ISSUE_TEMPLATE/other.yaml
Labels: relates-to: build

#738 build: bump up to micronaut 3.0.0-M5
  gradle.properties
  security-jwt/build.gradle
  test-suite-utils/build.gradle
Labels: type: dependency-upgrade
