Repository micronaut-projects/micronaut-security, pull requests merged in 2021-11, with the labels that each got.

#834 build: bump up test containers to 1.16.2
  security-oauth2/build.gradle
Labels: type: dependency-upgrade

#846 Micronaut build plugin
  build.gradle
  settings.gradle
Labels: relates-to: build

#847 [security] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#818 Support Keycloak in OpenID Connect end session endpoint
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/endsession/request/AuthorizationServer.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/endsession/request/EndSessionEndpointResolver.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/endsession/request/KeycloakEndSessionEndpoint.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/endsession/request/AuthorizationServerSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/endsession/request/KeycloakEndSessionEndpointSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/keycloak/KeycloakEndSessionEndpoint.groovy
  test-suite-utils/src/main/groovy/io/micronaut/security/testutils/Keycloak.groovy
Labels: type: enhancement
