Repository micronaut-projects/micronaut-security, pull requests merged in 2021-03, with the labels that each got.

#580 [security] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#586 test: add spock IGlobalExtension
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/Keycloak.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/KeycloakCleanup.groovy
  security-oauth2/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Labels: type: improvement

#587 ci: version to 2.4.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#560 build: ump up kotlin-stdlib-jdk8 to 1.4.31
  security-oauth2/build.gradle
  test-suite-kotlin/build.gradle
Labels: type: dependency-upgrade

#590 refactor: instantiate map only if log level debug
  security/src/main/java/io/micronaut/security/filters/SecurityFilter.java
Labels: type: improvement

#593 build: graalvm reflect-config.json for gralvm
  security-ldap/src/main/resources/META-INF/native-image/io.micronaut.security/ldap/reflect-config.json
Labels: relates-to: graal, type: bug

#592 build: del compileOnly graalvm.nativeimage:svm
  security-jwt/build.gradle
Labels: relates-to: build, relates-to: graal

#595 remove unuecessary repository block
  build.gradle
Labels: relates-to: build

#594 don't add `annotationProcessor "io.micronaut.docs:micronaut-docs-asciidoc-config-props:$micronautDocsVersion"` for example and `test-suite`
  build.gradle
Labels: relates-to: build

#598 remove githubBranch from gradle.properties
  gradle.properties
Labels: relates-to: build

#600 [security] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#611 feat: add unauthorized_scope_error and user_cancelled_authorize error codes
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorCode.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorCodeSpec.groovy
Labels: type: bug
