Repository micronaut-projects/micronaut-security, pull requests merged in 2022-11, with the labels that each got.

#1131 fix: decouple converter from config
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/configuration/CorsConfigurationSpec.groovy
  security/src/main/java/io/micronaut/security/config/DefaultInterceptUrlPatternModifier.java
  security/src/main/java/io/micronaut/security/config/InterceptUrlMapConverter.java
  security/src/main/java/io/micronaut/security/config/InterceptUrlPatternModifier.java
  security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java
  security/src/main/java/io/micronaut/security/rules/ConfigurationInterceptUrlMapRule.java
  security/src/test/groovy/io/micronaut/security/config/InterceptUrlMapConverterContextPathByDefaultSpec.groovy
  test-suite-tomcat-groovy/build.gradle
  test-suite-tomcat/build.gradle
Labels: type: bug

#1137 Stop publishing micronaut-test-utils to maven central
  test-suite-utils/build.gradle
Labels: relates-to: build

#1143 Fix dependency scope
  security-oauth2/build.gradle
Labels: type: bug

#1146 build: Micronaut Version 3.7.4
  gradle.properties
  gradle/libs.versions.toml
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/response/validation/DefaultOpenIdTokenResponseValidator.java
  security/build.gradle
  security/src/test/groovy/io/micronaut/docs/security/authorization/X509AuthorizationSpec.groovy
  security/src/test/resources/ssl/KeyStore.p12
  security/src/test/resources/ssl/TrustStore.jks
Labels: type: dependency-upgrade
