Repository micronaut-projects/micronaut-security, pull requests merged in 2022-03, with the labels that each got.

#928 add link to the X.509 guide
  src/main/docs/guide/authenticationStrategies/x509.adoc
Labels: type: docs

#940 ci: github action fetch-depth: 0
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#941 Make sensitive endpoints error by default
  gradle.properties
  security-jwt/src/test/groovy/io/micronaut/security/SensitiveEndpointRuleReplacement.groovy
  security/src/main/java/io/micronaut/security/rules/SensitiveEndpointRule.java
  security/src/test/groovy/io/micronaut/docs/security/securityRule/builtinendpoints/AuthenticationProviderUserPassword.groovy
  security/src/test/groovy/io/micronaut/docs/security/securityRule/builtinendpoints/BuiltInEndpointsSpec.groovy
  security/src/test/groovy/io/micronaut/docs/security/token/basicauth/BasicAuthSpec.groovy
  security/src/test/groovy/io/micronaut/security/HealthSensitivitySpec.groovy
  security/src/test/groovy/io/micronaut/security/SecurityDisabledSpec.groovy
  security/src/test/groovy/io/micronaut/security/authorization/AuthorizationSpec.groovy
  security/src/test/groovy/io/micronaut/security/token/basicauth/BasicAuthSpec.groovy
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/securityRule/builtInEndpointsAccess.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/sensitiveendpointrule/SensitiveEndpointRuleReplacement.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/sensitiveendpointrule/SensitiveEndpointRuleReplacementSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/sensitiveendpointrule/SensitiveEndpointRuleReplacement.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/sensitiveendpointrule/SensitveEndpointRuleReplacementTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/oauth2/docs/managementendpoints/SensitiveEndpointRuleReplacement.kt
  test-suite/src/test/java/io/micronaut/security/docs/sensitiveendpointrule/SensitiveEndpointRuleReplacement.java
  test-suite/src/test/java/io/micronaut/security/docs/sensitiveendpointrule/SensitiveEndpointRuleReplacementTest.java
Labels: relates-to: security

#947 ci: checkout v3
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: relates-to: build

#955 build: update build plugin to 5.2.3
  settings.gradle
Labels: relates-to: build

#957 ci: SuppressionFilter
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#960 build: nimbus jose from 9.20 to 9.21
  gradle.properties
Labels: type: dependency-upgrade

#961 build: bump up to serde to 1.0.0-RC3
  gradle.properties
Labels: relates-to: build

#963 update to micronaut serialization 1.0.0
  gradle.properties
Labels: relates-to: build

#964 test: dependencies upgrade reactor to 3.4.16 ldapsdk to 6.0.4
  security-ldap/build.gradle
Labels: type: dependency-upgrade

#968 ci: cache@v3 action-junit-report:v3.0.1 release target repository
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build
