Repository micronaut-projects/micronaut-security, pull requests merged in 2022-01, with the labels that each got.

#881 javadoc: SecurityFilter should mention SecurityFilter instead of JWT
  security/src/main/java/io/micronaut/security/rules/SecurityRule.java
Labels: type: docs

#882 fix: Logger name should be IpPatternsRule
  security/src/main/java/io/micronaut/security/rules/IpPatternsRule.java
Labels: type: bug

#883 doc: fix ldap configuration reference unresolved directive
  src/main/docs/guide/authenticationStrategies/ldap/configuration.adoc
Labels: type: docs

#879 build: Gradle to 7.3.3 from 7.3.2
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#892 Use official GraalVM GitHub Action
  .github/workflows/graalvm.yml
Labels: relates-to: build

#895 git: don't ignore build-logic/src/main/java/io/micronaut/build
  .gitignore
Labels: relates-to: build

#885 feat: redirect configuration toggeable
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/CookieLoginHandler.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandler.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationNoRedirectSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieClearerLogoutHandlerSpec.groovy
  security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java
  security-session/src/main/java/io/micronaut/security/session/SessionLogoutHandler.java
  security-session/src/test/groovy/io/micronaut/docs/security/session/SessionAuthenticationNoRedirectSpec.groovy
  security/src/main/java/io/micronaut/security/authentication/DefaultAuthorizationExceptionHandler.java
  security/src/main/java/io/micronaut/security/config/RedirectConfiguration.java
  security/src/main/java/io/micronaut/security/config/RedirectConfigurationProperties.java
  src/main/docs/guide/authenticationStrategies/session.adoc
  src/main/docs/guide/securityConfiguration/noRedirection.adoc
  src/main/docs/guide/toc.yml
Labels: type: improvement

#894 fix: basic auth must allow password with :
  security/src/main/java/io/micronaut/security/authentication/BasicAuthUtils.java
  security/src/test/groovy/io/micronaut/security/authentication/BasicAuthUtilsSpec.groovy
Labels: type: bug

#897 build: bump up micronaut to 3.2.4
  gradle.properties
Labels: type: dependency-upgrade

#900 build: bump up reactor-test to 3.4.14
  security-ldap/build.gradle
Labels: type: dependency-upgrade

#889 Use new JsonMapper abstraction for serde compatibility
  gradle.properties
  security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/KeysController.java
  security-oauth2/build.gradle
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/OpenIdClientFactory.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/state/JacksonStateSerDes.java
  security/build.gradle
  security/src/main/java/io/micronaut/security/authentication/Authentication.java
  security/src/main/java/io/micronaut/security/authentication/jackson/SecurityJacksonModule.java
  security/src/main/java/io/micronaut/security/endpoints/introspection/IntrospectionController.java
  security/src/test/groovy/io/micronaut/security/authentication/AuthenticationSerializationSpec.groovy
Labels: type: enhancement

#908 bump up micronaut to 3.0.0-M1
  gradle.properties
Labels: relates-to: build

#907 ci: add Gradle Enterprise badge
  README.md
Labels: relates-to: build

#906 build: bump up serde to 1.0.0-M5
  gradle.properties
Labels: type: dependency-upgrade

#912 build: bump up testcontainers to 1.16.3
  security-oauth2/build.gradle
Labels: type: dependency-upgrade

#914 build: add bom module
  gradle.properties
  security-bom/build.gradle
  security-jwt/build.gradle
  settings.gradle
Labels: relates-to: build

#916 ci: GraalVM github action from 21.3.0 to 22.0.0.2
  .github/workflows/graalvm.yml
  MAINTAINING.md
Labels: relates-to: build

#919 test: use ARM builds of selenium container on M1 macs
  test-suite-utils/src/main/resources/GebConfig.groovy
Labels: relates-to: build

#922 ci: update to junit-report-action 2.9.0
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
