Repository micronaut-projects/micronaut-security, pull requests merged in 2022-05, with the labels that each got.

#992 [security] Update common files for branch master
  .github/dependabot.yml
  .github/renovate.json
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  MAINTAINING.md
Labels: relates-to: build

#1014 Correct configuration setting name
  src/main/docs/guide/securityConfiguration/noRedirection.adoc
Labels: type: docs

#1018 doc: reject not found configuration reference
  security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java
Labels: type: docs

#1019 javadoc: use @value
  security/src/main/java/io/micronaut/security/config/SecurityConfigurationProperties.java
Labels: type: docs

#1022 fix: IpPatternsRule UNKNOWN if HttpRequest:getRemoteAddress throws
  security/src/main/java/io/micronaut/security/rules/IpPatternsRule.java
  security/src/test/groovy/io/micronaut/docs/security/securityRule/IpPatternSpec.groovy
Labels: type: bug

#1021 ci: graal 22.1.0
  .github/workflows/graalvm.yml
Labels: relates-to: build
