Repository micronaut-projects/micronaut-security, pull requests merged in 2022-08, with the labels that each got.

#1070 Improve readability and grammar
  src/main/docs/guide/authenticationStrategies/jwt/jwtEncryption.adoc
Labels: type: docs

#1076 test: test which verifies #983
  security/src/main/java/io/micronaut/security/endpoints/LoginController.java
  settings.gradle
  test-suite-tomcat-groovy/build.gradle
  test-suite-tomcat-groovy/src/test/groovy/tomcat/JwtLoginSpec.groovy
  test-suite-tomcat-groovy/src/test/resources/logback.xml
  test-suite-tomcat/build.gradle
  test-suite-tomcat/src/test/java/io/micronaut/security/test/tomcat/JwtLoginTest.java
  test-suite-tomcat/src/test/resources/logback.xml
Labels: type: bug

#1083 ci: junit report 3.3.3
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
