Repository micronaut-projects/micronaut-security, pull requests merged in 2023-02, with the labels that each got.

#1215 build: Micronaut Build 5.4.2
  settings.gradle
Labels: relates-to: build

#1220 ci: Github actions sync
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#1233 doc: document exception handlers
  src/main/docs/guide/exceptionHandlers.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#1231 bug: handle error code not AuthorizationErrorCode
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultAuthorizationErrorResponse.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultAuthorizationErrorResponseSpec.groovy
Labels: type: bug
