Repository micronaut-projects/micronaut-security, pull requests merged in 2023-05, with the labels that each got.

#1193 Enable aot
  .github/workflows/aot.yml
  gradle.properties
  gradle/libs.versions.toml
  security-aot/build.gradle.kts
  settings.gradle
  test-suite-aot-authserver/build.gradle
  test-suite-aot/build.gradle
Labels: relates-to: build

#1314 [security] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/graalvm.yml
  test-suite-graal/build.gradle
Labels: relates-to: build

#1308 doc: better security rules documentation (#1305)
  src/main/docs/guide/securityRule.adoc
  src/main/docs/guide/securityRule/interceptUrlMap.adoc
  src/main/docs/guide/securityRule/secured.adoc
Labels: type: docs

#1310 M3
  gradle/libs.versions.toml
  security-jwt/build.gradle
  security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/OauthController.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwksCacheSpec.groovy
  security-oauth2/build.gradle
  settings.gradle
  test-suite-geb/build.gradle.kts
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite-serde/build.gradle
  test-suite-tomcat-groovy/build.gradle
  test-suite-tomcat/build.gradle
  test-suite/build.gradle
Labels: type: dependency-upgrade

#1309 Expression language support for Authentication
  security-annotations/src/main/java/io/micronaut/security/annotation/expressions/SecuredEvaluationContextRegistrar.java
  security-annotations/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/OauthController.java
  security/src/main/java/io/micronaut/security/expressions/SecuredEvaluationContext.java
  security/src/main/java/io/micronaut/security/expressions/package-info.java
  security/src/main/java/io/micronaut/security/rules/SecuredAnnotationRule.java
  security/src/test/groovy/io/micronaut/docs/security/securityRule/secured/SecuredExpressionSpec.groovy
  src/main/docs/guide/securityRule/secured.adoc
  src/main/docs/guide/securityRule/secured/jakartaAnnotations.adoc
  src/main/docs/guide/securityRule/secured/securedExpression.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/build.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/securedexpressions/ExampleController.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/securedexpressions/SecuredExpressionsSpec.groovy
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/securedexpressions/ExampleController.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/securedexpressions/SecuredExpressionsTest.kt
  test-suite/build.gradle
  test-suite/src/test/java/io/micronaut/security/docs/securedexpressions/ExampleController.java
  test-suite/src/test/java/io/micronaut/security/docs/securedexpressions/SecuredExpressionsTest.java
Labels: type: enhancement

#1323 BREAKS: change Status for no redirect and cookie
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationNoRedirectSpec.groovy
  security/src/main/java/io/micronaut/security/token/cookie/CookieLoginHandler.java
  src/main/docs/guide/breaks.adoc
Labels: type: improvement, type: breaking

#1324 Security to M5
  build.gradle
  gradle.properties
  gradle/libs.versions.toml
  security-jwt/src/test/groovy/io/micronaut/security/token/propagation/TokenPropagationSpec.groovy
  test-suite-geb/build.gradle.kts
  test-suite-tomcat-groovy/src/test/groovy/tomcat/JwtLoginSpec.groovy
  test-suite-tomcat/src/test/java/io/micronaut/security/test/tomcat/JwtLoginTest.java
Labels: type: dependency-upgrade

#1328 Security + Tomcat fails with fails No active propagation context
  gradle/libs.versions.toml
  test-suite-tomcat-groovy/src/test/groovy/tomcat/JwtLoginSpec.groovy
  test-suite-tomcat/src/test/java/io/micronaut/security/test/tomcat/JwtLoginTest.java
Labels: type: regression, type: bug

#1329 Security TokenPropagation fails after update to M5
  security-jwt/src/test/groovy/io/micronaut/security/token/propagation/TokenPropagationSpec.groovy
  security/src/main/java/io/micronaut/security/token/propagation/TokenPropagationHttpClientFilter.java
  security/src/test/groovy/io/micronaut/security/propagation/TokenPropagationHttpClientFilterPathSpec.groovy
  security/src/test/groovy/io/micronaut/security/propagation/TokenPropagationHttpClientFilterSpec.groovy
Labels: type: regression, type: bug

#1335 [security] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
