Repository micronaut-projects/micronaut-security, pull requests merged in 2023-08, with the labels that each got.

#1408 doc: idtoken not custom OpenIdAuthenticationMapper
  src/main/docs/guide/oauth/flows/authorization-code/openid-authorization-code/openid-user-details.adoc
Labels: type: docs

#1407 [security] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#1409 more logging
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/IdTokenClaimsValidator.java
Labels: type: improvement

#1428 [security] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build
