Repository micronaut-projects/micronaut-security, pull requests merged in 2024-03, with the labels that each got.

#1617 Clarify non-blocking requirements in TokenValidator#validateToken javadoc
  security/src/main/java/io/micronaut/security/token/validator/TokenValidator.java
Labels: type: docs

#1625 Add locale and host to security events
  gradle.properties
  security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/DefaultOauthController.java
  security/src/main/java/io/micronaut/security/endpoints/LoginController.java
  security/src/main/java/io/micronaut/security/endpoints/LogoutController.java
  security/src/main/java/io/micronaut/security/event/LoginFailedEvent.java
  security/src/main/java/io/micronaut/security/event/LoginSuccessfulEvent.java
  security/src/main/java/io/micronaut/security/event/LogoutEvent.java
  security/src/main/java/io/micronaut/security/event/SecurityEvent.java
  security/src/main/java/io/micronaut/security/event/TokenValidatedEvent.java
  security/src/main/java/io/micronaut/security/token/TokenAuthenticationFetcher.java
  security/src/main/java/io/micronaut/security/token/cookie/TokenCookieClearerLogoutHandler.java
  security/src/test/groovy/io/micronaut/security/events/EventListenerSpec.groovy
  security/src/test/groovy/io/micronaut/security/token/TokenAuthenticationFetcherSpec.groovy
Labels: type: improvement

#1640 Fix Keycloak docker tests for 4.6.x
  build.gradle
  security-oauth2/build.gradle.kts
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdClient.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectOauthDisabledSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/OpenIdAuthorizationRedirectWithJustOpenIdSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/pkce/OpenIdAuthorizationPkceSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/pkce/OpenIdAuthorizationRedirectPkceSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/authorization/request/pkce/OpenIdAuthorizationRedirectWithJustOpenIdPkceSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/endpoint/endsession/request/KeycloakEndSessionEndpointSpec.groovy
  security-oauth2/src/test/groovy/io/micronaut/security/utils/KeycloakCleanup.groovy
  settings.gradle
  test-suite-geb/build.gradle.kts
  test-suite-geb/src/test/groovy/io/micronaut/security/oauth2/e2e/AuthenticationModeIdTokenSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/oauth2/e2e/OpenIdAuthorizationCodeSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookiePriorLoginSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieRefreshSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/token/jwt/cookie/OauthControllerEnabledSpec.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/utils/KeycloakCleanup.groovy
  test-suite-geb/src/test/groovy/io/micronaut/security/websockets/HomePageSpec.groovy
  test-suite-keycloak-16/src/main/java/io/micronaut/security/oauth2/keycloack/v16/Keycloak.java
  test-suite-keycloak-16/src/main/java/io/micronaut/security/oauth2/keycloack/v16/OperatingSystem.java
  test-suite-keycloak-16/src/main/resources/Dockerfile.keycloak
  test-suite-keycloak-docker/build.gradle
  test-suite-keycloak-docker/src/main/java/io/micronaut/security/oauth2/keycloak/docker/Keycloak.java
  test-suite-keycloak-docker/src/main/java/io/micronaut/security/oauth2/keycloak/docker/TestContainersUtils.java
Labels: relates-to: build

#1637 Update settings and remove groovy version
  gradle/libs.versions.toml
  settings.gradle
Labels: relates-to: build

#1641 Offload JWK Set fetching from the event loop
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
  security-jwt/src/test/groovy/io/micronaut/docs/jwks/JwksSpec.groovy
  security-oauth2/build.gradle.kts
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/JwksUriSignatureTimeoutSpec.groovy
  src/main/docs/guide/authenticationStrategies/jwt/jwtValidation/jwks.adoc
Labels: type: bug

#1635 `file:` prefix is not working for static jwks configurations
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignature.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignatureClasspathSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/StaticJwksSignatureFileSpec.groovy
Labels: type: bug
