Repository micronaut-projects/micronaut-security, pull requests merged in 2024-04, with the labels that each got.

#1665 breaks: delete deprecated code
  config/accepted-api-changes.json
  security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/validator/JwtClaimsValidatorRequestPassedSpec.groovy
  security-oauth2/src/main/java/io/micronaut/security/oauth2/client/DefaultOpenIdProviderMetadata.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/DefaultOpenIdAuthorizationResponseHandler.java
  src/main/docs/guide/breaks.adoc
Labels: type: breaking

#1674 [security] Update common files for branch 4.8.x
  .github/workflows/central-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1690 docs: clarify how to add annotation processor dependencies for Kotlin and Groovy projects
  src/main/docs/guide/authenticationStrategies/jwt.adoc
  src/main/docs/guide/authenticationStrategies/session.adoc
  src/main/docs/guide/gettingStarted.adoc
  src/main/docs/guide/securityRule/secured/jakartaAnnotations.adoc
Labels: type: docs
