Repository micronaut-projects/micronaut-security, pull requests merged in 2024-02, with the labels that each got.

#1577 [security] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1580 fix: U…Credentials bean-introspection-module=false
  security/src/main/java/io/micronaut/security/authentication/UsernamePasswordCredentials.java
  settings.gradle
  test-suite-jackson-databind-bean-introspection-module-false/build.gradle.kts
  test-suite-jackson-databind-bean-introspection-module-false/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/UsernamePasswordCredentialsBeanIntrospectionModuleFalseTest.java
  test-suite-jackson-databind-bean-introspection-module-false/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/UsernamePasswordCredentialsTest.java
  test-suite-jackson-databind-bean-introspection-module-false/src/test/resources/logback.xml
Labels: type: bug

#1582 fix: AccessRefreshToken bean-introspection-module
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/render/AccessRefreshTokenSpec.groovy
  security/src/main/java/io/micronaut/security/token/render/AccessRefreshToken.java
  test-suite-jackson-databind-bean-introspection-module-false/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/UsernamePasswordCredentialsBeanIntrospectionModuleFalseTest.java
  test-suite-jackson-databind-bean-introspection-module-false/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/UsernamePasswordCredentialsTest.java
Labels: type: bug

#1589 fix: don’t expose validation
  gradle/libs.versions.toml
  security-jwt/build.gradle.kts
  security-ldap/build.gradle.kts
  security-oauth2/build.gradle.kts
  security/build.gradle.kts
  settings.gradle
  test-suite-hibernate-validator/build.gradle.kts
  test-suite-hibernate-validator/src/test/java/io/micronaut/security/jacksondatabind/beanintrospectionfalse/LoginControllerValidationTest.java
  test-suite-hibernate-validator/src/test/resources/logback.xml
Labels: type: bug

#1594 doc: breaking change AuthenticationProvider<HttpRequest<?>>
  src/main/docs/guide/breaks.adoc
Labels: type: docs

#1593 doc: removal of SecurityRule#check RouteMatch arg
  src/main/docs/guide/breaks.adoc
Labels: type: docs

#1592 [security] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#1609 [security] Update common files for branch master
  .github/workflows/graalvm-dev.yml
Labels: relates-to: build

#1610 handle correctly authentication failure in imperative authentication providers
  security-jwt/src/test/groovy/io/micronaut/security/authentication/provider/HttpRequestAuthenticationProviderAuthenticationExceptionSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/authentication/provider/HttpRequestAuthenticationProviderAuthenticationResponseFailureSpec.groovy
  security-jwt/src/test/groovy/io/micronaut/security/authentication/provider/MultipleAuthenticationProviderAuthenticationResponseFailureSpec.groovy
  security/src/main/java/io/micronaut/security/authentication/Authenticator.java
Labels: type: bug

#1611 major: Move processors to separate module
  gradle.properties
  security-annotations/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  security-oauth2/build.gradle.kts
  security-processor/build.gradle.kts
  security-processor/src/main/java/io/micronaut/security/processor/JakartaDenyAllAnnotationMapper.java
  security-processor/src/main/java/io/micronaut/security/processor/JakartaPermitAllAnnotationMapper.java
  security-processor/src/main/java/io/micronaut/security/processor/JakartaRolesAllowedAnnotationMapper.java
  security-processor/src/main/java/io/micronaut/security/processor/package-info.java
  security-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  security/build.gradle.kts
  settings.gradle
  src/main/docs/guide/authenticationStrategies/jwt.adoc
  src/main/docs/guide/authenticationStrategies/session.adoc
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/gettingStarted.adoc
  src/main/docs/guide/securityRule/secured/jakartaAnnotations.adoc
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite-security-service/build.gradle.kts
  test-suite/build.gradle
Labels: status: next major version

#1616 doc: fix artifact id
  src/main/docs/guide/retrievingAuthenticatedUser/securityService.adoc
Labels: type: docs
