Repository micronaut-projects/micronaut-security, pull requests merged in 2024-10, with the labels that each got.

#1818 fix: support deprecated config micronaut.security.oauth2.clients.*.token.auth-method
  gradle/libs.versions.toml
  security-oauth2/src/main/java/io/micronaut/security/oauth2/configuration/endpoints/DefaultSecureEndpointConfiguration.java
  security-oauth2/src/test/java/io/micronaut/security/oauth2/configuration/OauthClientConfigurationTest.java
Labels: type: regression

#1824 JWKS Caching via Micronaut Cache
  gradle/libs.versions.toml
  security-jwt/build.gradle.kts
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/CacheableJwkSetFetcher.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksCacheConfigurationExistsCondition.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignatureConfiguration.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignatureConfigurationProperties.java
  security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/ReactorCacheJwkSetFetcher.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwksCacheSpec.groovy
  security/src/main/java/io/micronaut/security/endpoints/LoginController.java
  security/src/main/java/io/micronaut/security/endpoints/LogoutController.java
  security/src/main/java/io/micronaut/security/token/TokenAuthenticationFetcher.java
  settings.gradle
  src/main/docs/guide/authenticationStrategies/jwt/jwtValidation/jwks.adoc
  src/main/docs/guide/authenticationStrategies/jwt/jwtValidation/jwks/jwksCache.adoc
  src/main/docs/guide/toc.yml
  test-suite-jwks-cache/build.gradle.kts
  test-suite-jwks-cache/src/test/java/io/micronaut/security/token/jwt/signature/jwks/JwksCacheTest.java
  test-suite-jwks-cache/src/test/resources/logback.xml
Labels: type: regression

#1829 content-types JSON, form-url-encoded configurable
  security/build.gradle.kts
  security/src/main/java/io/micronaut/security/endpoints/ControllerConfiguration.java
  security/src/main/java/io/micronaut/security/endpoints/ControllerConfigurationProperties.java
  security/src/main/java/io/micronaut/security/endpoints/LoginController.java
  security/src/main/java/io/micronaut/security/endpoints/LoginControllerConfiguration.java
  security/src/main/java/io/micronaut/security/endpoints/LoginControllerConfigurationProperties.java
  security/src/main/java/io/micronaut/security/endpoints/LogoutController.java
  security/src/main/java/io/micronaut/security/endpoints/LogoutControllerConfigurationProperties.java
  security/src/main/java/io/micronaut/security/endpoints/OauthController.java
  security/src/main/java/io/micronaut/security/endpoints/OauthControllerConfigurationProperties.java
  security/src/test/java/io/micronaut/security/endpoints/LoginControllerConfigurationTest.java
  security/src/test/java/io/micronaut/security/endpoints/LoginControllerContentTypesForPostTest.java
  security/src/test/java/io/micronaut/security/endpoints/LogoutControllerConfigurationTest.java
  security/src/test/java/io/micronaut/security/endpoints/LogoutControllerContentTypesForPostTest.java
  security/src/test/java/io/micronaut/security/endpoints/OauthControllerConfigurationTest.java
  security/src/test/java/io/micronaut/security/endpoints/OauthControllerContentTypesForPostTest.java
Labels: type: improvement

#1830 [security] Update common files for branch 4.11.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1833 doc: @RolesAllowed and @Secured in the same method
  security/src/test/groovy/io/micronaut/security/rolesallowed/RolesAllowedSpec.groovy
  src/main/docs/guide/securityFilter/securityRule/secured/jakartaAnnotations.adoc
Labels: type: docs

#1832 @requires ann for HTTP Server classes and beans.
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/authorization/response/AuthorizationErrorResponseExceptionHandler.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/DefaultOauthController.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/routes/OauthRouteBuilder.java
Labels: type: bug
