Repository micronaut-projects/micronaut-security, pull requests merged in 2024-01, with the labels that each got.

#1526 Add Imperative AuthenticationProvider and Reactive AuthenticationProvider
  security-jwt/src/test/groovy/io/micronaut/docs/jwtclaimsoverride/CustomAuthenticationProvider.java
  security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwksSpec.groovy
  security-ldap/src/main/java/io/micronaut/security/ldap/LdapAuthenticationProvider.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OauthPasswordAuthenticationProvider.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OpenIdPasswordAuthenticationProvider.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/PasswordGrantFactory.java
  security-oauth2/src/test/groovy/io/micronaut/security/oauth2/client/condition/PasswordGrantConditionSpec.groovy
  security-session/src/test/groovy/io/micronaut/security/session/ContextPathSpec.groovy
  security/src/main/java/io/micronaut/security/authentication/AuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/AuthenticationProviderAdapter.java
  security/src/main/java/io/micronaut/security/authentication/AuthenticationProviderUtils.java
  security/src/main/java/io/micronaut/security/authentication/Authenticator.java
  security/src/main/java/io/micronaut/security/authentication/BasicAuthAuthenticationFetcher.java
  security/src/main/java/io/micronaut/security/authentication/provider/AuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/provider/HttpRequestAuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/provider/HttpRequestReactiveAuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/provider/ReactiveAuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/provider/package-info.java
  security/src/main/java/io/micronaut/security/endpoints/LoginController.java
  security/src/main/java/io/micronaut/security/endpoints/introspection/DefaultIntrospectionProcessor.java
  security/src/main/java/io/micronaut/security/endpoints/introspection/IntrospectionProcessor.java
  security/src/test/groovy/io/micronaut/docs/security/authentication/AuthenticationProviderUserPassword.groovy
  security/src/test/groovy/io/micronaut/docs/security/principalparam/AuthenticationProviderUserPassword.groovy
  security/src/test/groovy/io/micronaut/docs/security/token/basicauth/AuthenticationProviderUserPassword.groovy
  security/src/test/groovy/io/micronaut/docs/security/token/basicauth/AuthenticationProviderUserPassword.java
  security/src/test/groovy/io/micronaut/security/authentication/AuthenticatorAllImperativeSpec.groovy
  security/src/test/groovy/io/micronaut/security/authentication/AuthenticatorImperativeSpec.groovy
  security/src/test/groovy/io/micronaut/security/authentication/AuthenticatorSpec.groovy
  security/src/test/groovy/io/micronaut/security/authentication/ImperativeAuthenticationProviderSpec.groovy
  security/src/test/groovy/io/micronaut/security/authentication/ImperativeAuthenticationProviderUtilsTest.groovy
  security/src/test/groovy/io/micronaut/security/authentication/provider/HttpRequestAuthenticationProviderSpec.groovy
  security/src/test/groovy/io/micronaut/security/authentication/provider/HttpRequestReactiveAuthenticationProviderSpec.groovy
  security/src/test/java/io/micronaut/security/MockAuthenticationProvider.java
  src/main/docs/guide/authenticationProviders.adoc
  src/main/docs/guide/authenticationProviders/imperativeAuthenticationProviders.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/blockingauthenticationprovider/AuthenticationProviderTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/blockingauthenticationprovider/CustomAuthenticationProvider.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/reactiveauthenticationprovider/CustomAuthenticationProvider.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/security/docs/reactiveauthenticationprovider/ReactiveAuthenticationProviderTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/blockingauthenticationprovider/AuthenticationProviderTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/blockingauthenticationprovider/CustomAuthenticationProvider.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/managementendpoints/LoggersTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/reactiveauthenticationprovider/CustomAuthenticationProvider.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/reactiveauthenticationprovider/ReactiveAuthenticationProviderTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/securedexpressions/SecuredExpressionsTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/security/docs/sensitiveendpointrule/SensitveEndpointRuleReplacementTest.kt
  test-suite-utils-security/src/main/java/io/micronaut/security/testutils/authprovider/MockAuthenticationProvider.java
  test-suite/src/test/java/io/micronaut/security/docs/blockingauthenticationprovider/AuthenticationProviderTest.java
  test-suite/src/test/java/io/micronaut/security/docs/blockingauthenticationprovider/CustomAuthenticationProvider.java
  test-suite/src/test/java/io/micronaut/security/docs/reactiveauthenticationprovider/CustomAuthenticationProvider.java
  test-suite/src/test/java/io/micronaut/security/docs/reactiveauthenticationprovider/ReactiveAuthenticationProviderTest.java
Labels: type: enhancement

#1550 [security] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1563 revert breaking change
  config/accepted-api-changes.json
  security-ldap/src/main/java/io/micronaut/security/ldap/LdapAuthenticationProvider.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OauthPasswordAuthenticationProvider.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/OpenIdPasswordAuthenticationProvider.java
  security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/password/PasswordGrantFactory.java
  security/src/main/java/io/micronaut/security/authentication/AuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/Authenticator.java
  security/src/main/java/io/micronaut/security/authentication/BasicAuthAuthenticationFetcher.java
  security/src/main/java/io/micronaut/security/authentication/provider/ExecutorAuthenticationProvider.java
  security/src/main/java/io/micronaut/security/authentication/provider/ReactiveAuthenticationProviderAdapter.java
  security/src/main/java/io/micronaut/security/endpoints/LoginController.java
  security/src/test/groovy/io/micronaut/security/authentication/AuthenticatorSpec.groovy
  security/src/test/groovy/io/micronaut/security/authentication/DeprecatedAuthenticationProviderStillWorksSpec.groovy
Labels: type: bug

#1567 [security] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
