Repository micronaut-projects/micronaut-security, pull requests merged in 2025-09, with the labels that each got.

#2020 [security] Update common files for branch 4.15.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#2016 Update to Apache Geb 8
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2026 security: don’t log token
  security/build.gradle.kts
  security/src/main/java/io/micronaut/security/token/reader/DefaultTokenResolver.java
  security/src/test/groovy/io/micronaut/security/token/reader/DefaultTokenResolverSpec.groovy
Labels: relates-to: security
